---
apiVersion: v1
kind: Pod
metadata:
  name: mm101-tutorial-frontend
  namespace: default
spec:
  containers:
    - name: mm101-tutorial-frontend
      image: jarmex/mm101-tutorial-frontend:latest
      imagePullPolicy: Always
  hostname: mm101-tutorial-frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: mm101-tutorial-matchfunction
  namespace: default
  labels:
    app: mm101-tutorial
    component: matchfunction
spec:
  containers:
    - name: mm101-tutorial-matchfunction
      image: jarmex/mm101-tutorial-matchfunction:latest
      imagePullPolicy: Always
      ports:
        - name: grpc
          containerPort: 50502
---
kind: Service
apiVersion: v1
metadata:
  name: mmf
  namespace: default
  labels:
    app: mm101-tutorial
    component: matchfunction
spec:
  selector:
    app: mm101-tutorial
    component: matchfunction
  clusterIP: None
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 50502
---
